name: latihan1_jamil002
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.8
  gallery_image_viewer: ^1.2.0
  geolocator: ^11.0.0
  latlong2: ^0.9.1
  path_provider: ^2.1.3
  sqflite: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
